### ISSUE TITLE
Any Specific reason to use mongodb and Moped authenticator

### ISSUE THREAD

**Issue by AjayBarot** [codescrum/casino-sso-server-example#1]
@jpamaya @luxflux @gato-omega @pencil  : Hi I am trying to implement the same app without mongodb (using active_record orm). 

In casino-sso-server side I am using same database as mention in database.yml.

```
development:
  sso_example_database:
    authenticator: "ActiveRecord"
    options:
      connection:
        adapter: "mysql2"
        host: "localhost"
        username: "root"
        password: 
        database: "SSOExampleApp"
      table: "users"
      username_column: "email"
      password_column: "encrypted_password"
```

**database.yml**

```
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: SSOExampleApp
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
```

and I added users table into `SSOExampleApp`. In existing app you moved users table into mongodb . Any specific reason for using mongodb.

How to access mysql database over HTTP ? Basically I want to replace mongodb with mysql.

**Issue:** : I get Incorrect username or password on login. Let me know your thought on this.

Thanks & Regards

Ajay
